bg: "/configs/constellations/imgs/bg.jpeg"
stars:
  - id: "eevee"
    name: "Eevee"
    img: "/configs/constellations/imgs/eevee.jpg"
    size: 0.5
    pitch: 0.5
    yaw: 1.57
    distance: 4
    zoom_factor: 10
    text:
      title: "a really cute pokemon"
      content: > 
        such a fluffy lil guy
        like oh my god they are so **cute**
        [visit their friend](LINK_STAR among)
  - id: "among"
    name: "Among Us?!"
    img: "/configs/constellations/imgs/eevee.jpg"
    size: 2
    pitch: 0.5
    yaw: -1.57
    distance: 8
    zoom_factor: 10
    text:
      title: "could be an imposter"
      content: > 
        i don't know
constellations:
  - id: "eeveelutions"
    name: "Eeveelutions"
    members:
      - "eevee"
    links: []